name: Create Releases

on:
  schedule:
    - cron: '0 0 1 * *'  # 00:00 on the 1st of every month (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set run date as release tag and filename date
      id: run_date
      run: |
        echo "release_tag=$(date -u +%F)" >> $GITHUB_OUTPUT
        echo "release_date_nodash=$(date -u +%Y%m%d)" >> $GITHUB_OUTPUT

    - name: Install man-db and zip md5sum tools
      run: |
        sudo apt-get update
        sudo apt-get install -y man man-db zip groff ghostscript

    - name: Get latest release version for code2prompt
      id: get_version
      run: |
        LATEST_VERSION=$(curl -s https://api.github.com/repos/mufeedvh/code2prompt/releases/latest | jq -r '.tag_name')
        echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT

    - name: Construct download URL of code2prompt
      id: download_url
      run: |
        VERSION=${{ steps.get_version.outputs.version }}
        URL="https://github.com/mufeedvh/code2prompt/releases/download/$VERSION/code2prompt-x86_64-unknown-linux-gnu"
        echo "url=$URL" >> $GITHUB_OUTPUT

    - name: Download and install code2prompt
      run: |
        URL=${{ steps.download_url.outputs.url }}
        curl -L "$URL" -o code2prompt
        chmod +x code2prompt
        sudo mv code2prompt /usr/local/bin/

    - name: Update man pages
      run: |
        sudo mandb

    - name: Generate PDF files from man pages
      run: |
        chmod +x generate_pdf.sh
        ./generate_pdf.sh
        mv _pdf man-pdf

    - name: Compress man page pdf and clean
      run: |
        zip -r man-db-${{ steps.run_date.outputs.release_date_nodash }}-en-pdf.zip man-pdf
        rm -rf man-pdf

    - name: Copy man page files to root dir
      run: |
        cp -a /usr/share/man ./man

    - name: Compress all .gz files
      run: |
        zip -r man-db-${{ steps.run_date.outputs.release_date_nodash }}.zip man

    - name: Compress en .gz files
      run: |
        zip -r man-db-${{ steps.run_date.outputs.release_date_nodash }}-en.zip man/man[1-9]

    - name: Do code2prompt
      run: |
        sections=("man1" "man2" "man3" "man4" "man5" "man6" "man7" "man8")
        for section in "${sections[@]}"; do
          output_file="${section}.txt"
          echo "Running: code2prompt.exe $section -o $output_file"
          code2prompt.exe "man/$section" -o "$output_file"
        done

    - name: Decompress EN .gz files and clean
      run: |
        chmod +x decompress_gz.sh
        ./decompress_gz.sh man
        rm -rf man
        mv _decompress man

    - name: Compress EN unzipped files
      run: |
        zip -r man-db-${{ steps.run_date.outputs.release_date_nodash }}-en-unzipped.zip man/man[1-9]

    - name: Rename EN unzipped files to *.txt
      run: |
        chmod +x add_suffix_txt.sh
        ./add_suffix_txt.sh man

    - name: Compress EN *.txt and clean
      run: |
        zip -r man-db-${{ steps.run_date.outputs.release_date_nodash }}-en-unzipped-txt.zip man/man[1-9]
        rm -rf man

    - name: Create GitHub Release and upload files
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
      with:
        tag_name: ${{ steps.run_date.outputs.release_tag }}
        name: ${{ steps.run_date.outputs.release_tag }}
        files: |
          man-db-${{ steps.run_date.outputs.release_date_nodash }}*.zip
          man-db-${{ steps.run_date.outputs.release_date_nodash }}*.txt
