name: Create Releases

on:
  schedule:
    - cron: '0 0 1 * *'  # 00:00 on the 1st of every month (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set run date as release tag and filename date
      id: run_date
      run: |
        echo "release_tag=$(date -u +%F)" >> $GITHUB_OUTPUT
        echo "release_date_nodash=$(date -u +%Y%m%d)" >> $GITHUB_OUTPUT

    - name: Install man-db and zip md5sum tools
      run: |
        sudo apt-get update
        sudo apt-get install -y man man-db zip groff

    - name: Update man pages
      run: |
        sudo mandb

    - name: Generate PDF files from man pages
      run: |
        chmod +x generate_pdf.sh
        ./generate_pdf.sh

    - name: Compress man page pdf and clear
      run: |
        zip -r man-db-${{ steps.run_date.outputs.release_date_nodash }}-en-pdf.zip _pdf
        rm -rf _pdf

    - name: Compress all .gz files
      run: |
        # Not modify local files
        cp -a /usr/share/man ./man
        zip -r man-db-${{ steps.run_date.outputs.release_date_nodash }}.zip man

    - name: Compress en .gz files
      run: |
        zip -r man-db-${{ steps.run_date.outputs.release_date_nodash }}-en.zip man/man[1-9]

    - name: Decompress EN .gz files and clear
      run: |
        chmod +x decompress_gz.sh
        ./decompress_gz.sh man
        rm -rf man
        mv _decompress man

    - name: Compress EN unzipped files
      run: |
        zip -r man-db-${{ steps.run_date.outputs.release_date_nodash }}-en-unzipped.zip man/man[1-9]

    - name: Rename EN unzipped files to *.txt
      run: |
        chmod +x add_suffix_txt.sh
        ./add_suffix_txt.sh man

    - name: Compress EN *.txt and clear
      run: |
        zip -r man-db-${{ steps.run_date.outputs.release_date_nodash }}-en-unzipped-txt.zip man/man[1-9]
        rm -rf man

    - name: Create GitHub Release and upload files
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
      with:
        tag_name: ${{ steps.run_date.outputs.release_tag }}
        name: ${{ steps.run_date.outputs.release_tag }}
        files: |
          man-db-${{ steps.run_date.outputs.release_date_nodash }}*.zip
